-- CREATE DATABASE POSSym;

DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS employees_positions;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS menu_ingredient;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS discounts;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS tips;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS reservations;

CREATE TABLE restaurants (
    id SERIAL PRIMARY KEY;
    name VARCHAR(64) NOT NULL;
    company VARCHAR(64) NOT NULL;
    address VARCHAR(64) NOT NULL;
    country VARCHAR(64) NOT NULL;
    city VARCHAR(64) NOT NULL;
    state VARCHAR(64) NOT NULL;
    storeManager VARCHAR(64) NOT NULL;
    numEmployees INT DEFAULT 0;
    createdAt CURRENT TIMESTAMP;
);

CREATE TABLE employees (
    id SERIAL PRIMARY KEY;
    
)