"""add pin and password to employees

Revision ID: e2f0eb0c6ca9
Revises: b575264d4794
Create Date: 2026-05-24 01:34:29.637698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f0eb0c6ca9'
down_revision: Union[str, None] = 'b575264d4794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('employees', sa.Column('pin', sa.String(length=255), nullable=False))
    op.add_column('employees', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'tables', 'orders', ['order_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('employees', 'password')
    op.drop_column('employees', 'pin')
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
