"""fix 'catgeory_id' typo

Revision ID: ff15666eea53
Revises: 5017999bcfb8
Create Date: 2026-06-12 22:16:57.017093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff15666eea53'
down_revision: Union[str, None] = '5017999bcfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('menu_items_cateogry_id_fkey', 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu_categories', ['category_id'], ['id'])
    op.drop_column('menu_items', 'cateogry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('cateogry_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key('menu_items_cateogry_id_fkey', 'menu_items', 'menu_categories', ['cateogry_id'], ['id'])
    op.drop_column('menu_items', 'category_id')
    # ### end Alembic commands ###
